dist: xenial
sudo: required

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - python setup.py install
  - pip install pytest flake8 pytest-cov
  - pip install coveralls

script:
  - pytest --cov=pyspx
  - flake8 src/pyspx

after_success:
  - coveralls
